version: '3'
services:
  frontend:
    build: ./frontend/
    ports:
     - "80:80"
    restart: always
    links:
      - backend
  #database:
  #  build:
  #    context: ./database
  #    args:
  #        - MYSQL_DATABASE=${MYSQL_DATABASE}
  #        - MYSQL_USER=${MYSQL_USER}
  #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #  ports:
  #          - "${MYSQL_PORT}:3306"
  #  restart: always
  #  volumes:
  #  - ./mysql:/var/lib/mysql

  backend:
    build: ./backend/
    ports:
     - "5000:5000"
    restart: always
    volumes:
     - ~/logs/:/root/logs/
  